/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MediaTemplatesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  mediaLibrary: [],
  defaultMediaFolder: "Media",
  templateFolder: "Templates/Media",
  autoCreateFolders: true,
  openAfterCreate: true
};

// src/SettingsTab.ts
var import_obsidian2 = require("obsidian");

// src/AddMediaModal.ts
var import_obsidian = require("obsidian");
var MEDIA_TYPES = [
  { value: "tv-show", label: "TV Show" },
  { value: "movie", label: "Movie" },
  { value: "anime", label: "Anime" },
  { value: "miniseries", label: "Mini-series" },
  { value: "limited-series", label: "Limited Series" },
  { value: "documentary", label: "Documentary" }
];
var MEDIA_STATUSES = [
  { value: "watching", label: "Watching" },
  { value: "completed", label: "Completed" },
  { value: "planned", label: "Plan to Watch" },
  { value: "on-hold", label: "On Hold" },
  { value: "dropped", label: "Dropped" },
  { value: "rewatching", label: "Rewatching" }
];
var AddMediaModal = class extends import_obsidian.Modal {
  constructor(app, callback, existing) {
    super(app);
    this.callback = callback;
    this.isEdit = !!existing;
    this.draft = existing ? { ...existing } : {
      type: "tv-show",
      status: "watching",
      genres: [],
      tags: [],
      noteFolder: ""
    };
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("media-templates-modal");
    contentEl.createEl("h2", {
      text: this.isEdit ? "Edit Media" : "Add Media to Library"
    });
    new import_obsidian.Setting(contentEl).setName("Title").setDesc("Name of the show or movie").addText((text) => {
      var _a;
      text.setPlaceholder("Breaking Bad").setValue((_a = this.draft.title) != null ? _a : "").onChange((v) => this.draft.title = v);
      if (!this.isEdit) {
        setTimeout(() => text.inputEl.focus(), 50);
      }
    });
    new import_obsidian.Setting(contentEl).setName("Type").addDropdown((dd) => {
      var _a;
      for (const { value, label } of MEDIA_TYPES) {
        dd.addOption(value, label);
      }
      dd.setValue((_a = this.draft.type) != null ? _a : "tv-show");
      dd.onChange((v) => this.draft.type = v);
    });
    new import_obsidian.Setting(contentEl).setName("Status").addDropdown((dd) => {
      var _a;
      for (const { value, label } of MEDIA_STATUSES) {
        dd.addOption(value, label);
      }
      dd.setValue((_a = this.draft.status) != null ? _a : "watching");
      dd.onChange((v) => this.draft.status = v);
    });
    new import_obsidian.Setting(contentEl).setName("Year").setDesc("Start year (e.g. 2008)").addText((text) => {
      text.setPlaceholder("2008").setValue(this.draft.year ? String(this.draft.year) : "").onChange((v) => {
        const n = parseInt(v);
        this.draft.year = isNaN(n) ? void 0 : n;
      });
    });
    new import_obsidian.Setting(contentEl).setName("Genres").setDesc("Comma-separated list (e.g. Drama, Crime, Thriller)").addText((text) => {
      var _a;
      text.setPlaceholder("Drama, Crime").setValue(((_a = this.draft.genres) != null ? _a : []).join(", ")).onChange((v) => {
        this.draft.genres = v.split(",").map((s) => s.trim()).filter(Boolean);
      });
    });
    new import_obsidian.Setting(contentEl).setName("Note Folder").setDesc(
      "Vault path where notes for this media will be created. Leave blank to use the plugin default."
    ).addText((text) => {
      var _a;
      text.setPlaceholder("Media/Breaking Bad").setValue((_a = this.draft.noteFolder) != null ? _a : "").onChange((v) => this.draft.noteFolder = v);
    });
    new import_obsidian.Setting(contentEl).setName("Tags").setDesc("Extra tags (comma-separated), in addition to automatic media tags").addText((text) => {
      var _a;
      text.setPlaceholder("netflix, favorite").setValue(((_a = this.draft.tags) != null ? _a : []).join(", ")).onChange((v) => {
        this.draft.tags = v.split(",").map((s) => s.trim()).filter(Boolean);
      });
    });
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText(this.isEdit ? "Save Changes" : "Add to Library").setCta().onClick(() => this.submit())
    ).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => this.close())
    );
  }
  submit() {
    var _a, _b, _c, _d, _e, _f, _g;
    const title = ((_a = this.draft.title) != null ? _a : "").trim();
    if (!title) {
      new import_obsidian.Notice("Please enter a title.");
      return;
    }
    const media = {
      id: (_b = this.draft.id) != null ? _b : crypto.randomUUID(),
      title,
      type: (_c = this.draft.type) != null ? _c : "tv-show",
      status: (_d = this.draft.status) != null ? _d : "watching",
      genres: (_e = this.draft.genres) != null ? _e : [],
      year: this.draft.year,
      tags: (_f = this.draft.tags) != null ? _f : [],
      noteFolder: ((_g = this.draft.noteFolder) != null ? _g : "").trim() || `Media/${title}`
    };
    this.close();
    this.callback(media);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/SettingsTab.ts
var SettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Media Templates" });
    containerEl.createEl("h3", { text: "General" });
    new import_obsidian2.Setting(containerEl).setName("Default media folder").setDesc(
      "Vault path where notes are created when a media entry has no dedicated folder set."
    ).addText((text) => {
      text.setPlaceholder("Media").setValue(this.plugin.settings.defaultMediaFolder).onChange(async (v) => {
        this.plugin.settings.defaultMediaFolder = v.trim() || "Media";
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Template folder").setDesc(
      "Where the plugin's Templater template files live (for standalone Templater use)."
    ).addText((text) => {
      text.setPlaceholder("Templates/Media").setValue(this.plugin.settings.templateFolder).onChange(async (v) => {
        this.plugin.settings.templateFolder = v.trim() || "Templates/Media";
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Auto-create folders").setDesc("Automatically create sub-folders when a note is created.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.autoCreateFolders).onChange(async (v) => {
        this.plugin.settings.autoCreateFolders = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Open note after creating").setDesc("Switch to the new note immediately after it is created.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.openAfterCreate).onChange(async (v) => {
        this.plugin.settings.openAfterCreate = v;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Media Library" });
    new import_obsidian2.Setting(containerEl).setName("Add media").setDesc("Add a new show or movie to your library.").addButton((btn) => {
      btn.setButtonText("+ Add media").setCta().onClick(() => {
        new AddMediaModal(this.app, async (media) => {
          this.plugin.settings.mediaLibrary.push(media);
          await this.plugin.saveSettings();
          this.display();
        }).open();
      });
    });
    const library = this.plugin.settings.mediaLibrary;
    if (library.length === 0) {
      containerEl.createEl("p", {
        text: "Your library is empty. Add a show or movie above to get started.",
        cls: "setting-item-description"
      });
    } else {
      for (const media of library) {
        this.renderMediaEntry(containerEl, media);
      }
    }
  }
  renderMediaEntry(container, media) {
    var _a;
    const s = new import_obsidian2.Setting(container).setName(media.title).setDesc(
      [
        media.type,
        media.year,
        media.genres.length ? media.genres.join(", ") : null,
        `Status: ${media.status}`,
        `Folder: ${media.noteFolder}`
      ].filter(Boolean).join("  \xB7  ")
    ).addButton((btn) => {
      btn.setButtonText("Edit").onClick(() => {
        new AddMediaModal(
          this.app,
          async (updated) => {
            const idx = this.plugin.settings.mediaLibrary.findIndex(
              (m) => m.id === media.id
            );
            if (idx !== -1) {
              this.plugin.settings.mediaLibrary[idx] = updated;
              await this.plugin.saveSettings();
              this.display();
            }
          },
          media
        ).open();
      });
    }).addButton((btn) => {
      btn.setButtonText("Delete").setWarning().onClick(async () => {
        this.plugin.settings.mediaLibrary = this.plugin.settings.mediaLibrary.filter((m) => m.id !== media.id);
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const statusColors = {
      watching: "var(--color-green)",
      completed: "var(--color-blue)",
      planned: "var(--color-yellow)",
      dropped: "var(--color-red)",
      "on-hold": "var(--color-orange)",
      rewatching: "var(--color-purple)"
    };
    const badge = s.nameEl.createEl("span", {
      text: ` ${media.status}`,
      cls: "media-templates-badge"
    });
    badge.style.color = (_a = statusColors[media.status]) != null ? _a : "inherit";
    badge.style.fontSize = "0.8em";
    badge.style.marginLeft = "0.5em";
  }
};

// src/CreateNoteModal.ts
var import_obsidian3 = require("obsidian");

// src/noteTypes.ts
var NOTE_TYPES = [
  {
    id: "series-index",
    label: "Series Index",
    description: "Master hub note for a show or movie",
    subFolder: "",
    asksForSeason: false,
    asksForEpisode: false
  },
  {
    id: "season-overview",
    label: "Season Overview",
    description: "Summary and notes for an entire season or arc",
    subFolder: "Seasons",
    showOnlyFor: ["tv-show", "anime", "miniseries", "limited-series"],
    asksForSeason: true,
    asksForEpisode: false
  },
  {
    id: "episode",
    label: "Episode",
    description: "Notes for a single episode",
    subFolder: "Episodes",
    showOnlyFor: ["tv-show", "anime", "miniseries", "limited-series"],
    asksForSeason: true,
    asksForEpisode: true
  },
  {
    id: "character",
    label: "Character",
    description: "Character profile \u2014 history, traits, arcs, relationships",
    subFolder: "Characters"
  },
  {
    id: "location",
    label: "Location",
    description: "Place in the world \u2014 geography, history, inhabitants",
    subFolder: "World/Locations"
  },
  {
    id: "magic-system",
    label: "Magic System",
    description: "Power system \u2014 rules, costs, practitioners, lore",
    subFolder: "World/Magic & Powers"
  },
  {
    id: "technology",
    label: "Technology",
    description: "Device, science, or invention \u2014 function, specs, significance",
    subFolder: "World/Technology"
  },
  {
    id: "vehicle",
    label: "Vehicle",
    description: "Ship, car, aircraft, or other vehicle \u2014 specs and history",
    subFolder: "World/Vehicles"
  },
  {
    id: "creature-species",
    label: "Creature / Species",
    description: "Non-human creature or alien species",
    subFolder: "World/Creatures & Species"
  },
  {
    id: "item-artifact",
    label: "Item / Artifact",
    description: "Notable object \u2014 weapon, MacGuffin, relic, tool",
    subFolder: "World/Items & Artifacts"
  },
  {
    id: "faction-organization",
    label: "Faction / Organization",
    description: "Government, cult, corporation, crew, or any group",
    subFolder: "World/Factions & Organizations"
  },
  {
    id: "timeline-event",
    label: "Timeline Event",
    description: "In-universe historical or story event",
    subFolder: "Timeline"
  },
  {
    id: "plot-thread",
    label: "Plot Thread",
    description: "Ongoing story thread, mystery, or sub-plot",
    subFolder: "Narrative"
  },
  {
    id: "theory",
    label: "Theory",
    description: "Fan theory or analytical hypothesis",
    subFolder: "Analysis"
  }
];
function getNoteTypeInfo(id) {
  const info = NOTE_TYPES.find((t) => t.id === id);
  if (!info) throw new Error(`Unknown note type: ${id}`);
  return info;
}
function toSlug(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
function pad2(n) {
  if (!n) return "01";
  return n.padStart(2, "0");
}
function buildNoteContent(ctx) {
  var _a, _b;
  const slug = toSlug(ctx.media.title);
  const year = ctx.media.year ? String(ctx.media.year) : "";
  const vars = {
    MEDIATITLE: ctx.media.title,
    MEDIASLUG: slug,
    MEDIATYPE: ctx.media.type,
    MEDIAGENRES: ctx.media.genres.join(", ") || "",
    MEDIAYEAR: year,
    SEASON: (_a = ctx.season) != null ? _a : "1",
    EPISODE: (_b = ctx.episode) != null ? _b : "1",
    EPISODECODE: ctx.season ? `S${pad2(ctx.season)}E${pad2(ctx.episode)}` : "",
    NOTETITLE: ctx.title
  };
  const builders = {
    "series-index": buildSeriesIndex,
    "season-overview": buildSeasonOverview,
    episode: buildEpisode,
    character: buildCharacter,
    location: buildLocation,
    "magic-system": buildMagicSystem,
    technology: buildTechnology,
    vehicle: buildVehicle,
    "creature-species": buildCreatureSpecies,
    "item-artifact": buildItemArtifact,
    "faction-organization": buildFactionOrganization,
    "timeline-event": buildTimelineEvent,
    "plot-thread": buildPlotThread,
    theory: buildTheory
  };
  return builders[ctx.noteType](vars);
}
function buildSeriesIndex(v) {
  return `---
tags:
  - series-index
  - media/${v.MEDIASLUG}
title: "${v.MEDIATITLE}"
type: ${v.MEDIATYPE}
status: watching
year: ${v.MEDIAYEAR}
genres: [${v.MEDIAGENRES}]
rating:
cover:
---

# ${v.MEDIATITLE}

> [!info] Series Info
> **Type**: ${v.MEDIATYPE}
> **Year**: ${v.MEDIAYEAR}
> **Genres**: ${v.MEDIAGENRES}
> **Status**: Watching
> **Rating**:

## Description



## Seasons

| Season | Episodes | Status | Notes |
|--------|----------|--------|-------|
| 1      |          |        |       |

## Characters

### Main Cast

-

### Supporting

-

## World

### Locations

-

### Magic / Powers

-

### Technology

-

### Factions & Organizations

-

### Creatures & Species

-

### Items & Artifacts

-

## Timeline

-

## Themes

-

## My Notes & Analysis



## External Links

- [IMDb]()
- [Wikipedia]()
`;
}
function buildSeasonOverview(v) {
  return `---
tags:
  - season
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
season: ${v.SEASON}
episodes:
air_date_start:
air_date_end:
status: unwatched
rating:
---

# ${v.MEDIATITLE} \u2014 Season ${v.SEASON}

> [!info] Season Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Season**: ${v.SEASON}
> **Episodes**:
> **Aired**:

## Main Arc



## Episode List

| # | Title | Rating | Notes |
|---|-------|--------|-------|
| 1 |       |        |       |

## Key Developments

### Character Arcs



### World-Building



### Major Plot Twists



## New Additions

### New Characters

-

### New Locations

-

### New Concepts / Systems

-

## Deaths & Departures

-

## Season Themes

-

## Connections

- **Previous Season**:
- **Next Season**:

## Rating & Review



## Notes

`;
}
function buildEpisode(v) {
  return `---
tags:
  - episode
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
season: ${v.SEASON}
episode: ${v.EPISODE}
title: "${v.NOTETITLE}"
air_date:
directed_by:
written_by:
status: unwatched
rating:
---

# ${v.NOTETITLE}

> [!info] Episode Info
> **Show**: [[${v.MEDIATITLE}]]
> **Season ${v.SEASON}, Episode ${v.EPISODE}** \u2014 ${v.EPISODECODE}
> **Air Date**:
> **Director**:
> **Writer**:

## Synopsis

> [!abstract] Brief Synopsis
>

## Key Events

1.
2.
3.

## Character Focus

| Character | Arc / Development |
|-----------|------------------|
|           |                  |

## New This Episode

### Characters Introduced

-

### Locations Introduced

-

### Concepts / Reveals

-

## World-Building

> [!example] Lore Drops
> -

## Foreshadowing & Callbacks

- **Foreshadows**:
- **Callbacks to**:

## Memorable Quotes

> ""
> \u2014

## Analysis & Notes



## Episode Connections

- **Previous**:
- **Next**:
`;
}
function buildCharacter(v) {
  return `---
tags:
  - character
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
aliases: []
status: alive
affiliation:
role: supporting
first_appearance:
last_appearance:
actor:
---

# ${v.NOTETITLE}

> [!info] Character Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Status**: Alive
> **Role**:
> **Affiliation**:
> **Portrayed by**:

## Description

### Physical Appearance



### Personality



## Background

### History



### Backstory Reveals

-

## Abilities & Skills

-

## Relationships

| Character | Relationship | Notes |
|-----------|-------------|-------|
|           |             |       |

## Character Arc

### Season by Season



## Key Moments

-

## Memorable Quotes

> ""
> \u2014 ${v.NOTETITLE}

## Appearances

-

## Analysis

### Themes & Symbolism



### Fan Theories



`;
}
function buildLocation(v) {
  return `---
tags:
  - location
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
type:
first_appearance:
status:
---

# ${v.NOTETITLE}

> [!info] Location Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Type**:
> **Status**:

## Description

### Physical Description



### Atmosphere / Feel



## Geography & Layout

### Notable Areas

-

### Map / Diagram



## History

### Origins



### Key Historical Events

-

## Inhabitants & Control

### Notable Residents / Rulers

-

### Factions Present

-

## Strategic Importance



## Connections

### Nearby Locations

-

### Access Points

-

## Appearances

-

## Notes & Analysis

`;
}
function buildMagicSystem(v) {
  return `---
tags:
  - magic-system
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
type:
source_of_power:
---

# ${v.NOTETITLE}

> [!info] System Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Type**:
> **Source of Power**:

## Fundamental Rules

> [!important] Hard Rules
> 1.
> 2.
> 3.

## How It Works

### Mechanism



### Source of Power



### Activation / Casting



## Limitations & Costs

> [!warning] Limitations
> -
> -

## Tiers & Levels

| Level | Description | Known Practitioners |
|-------|-------------|---------------------|
|       |             |                     |

## Known Practitioners

| Character | Ability Level | Specialization |
|-----------|--------------|----------------|
|           |              |                |

## Notable Uses

-

## History & Lore

### Origins



### Evolution Over Time



## Mysteries & Questions

> [!question] Unanswered Questions
> -
> -

## Theories

-
`;
}
function buildTechnology(v) {
  return `---
tags:
  - technology
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
category:
creator:
status:
first_appearance:
---

# ${v.NOTETITLE}

> [!info] Tech Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Category**:
> **Creator**:
> **Status**:

## Purpose & Function

### Primary Function



### Secondary Uses



## How It Works

### Mechanism



### Power Source



## Specifications

| Attribute | Value |
|-----------|-------|
| Category  |       |
| Creator   |       |
| Era / Date |      |
| Status    |       |

## Capabilities

-

## Limitations

-

## Who Has Access

-

## History

### Development / Discovery



### Key Events

-

## Impact on the World



## Appearances

-

## Notes & Analysis

`;
}
function buildVehicle(v) {
  return `---
tags:
  - vehicle
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
type:
owner:
crew:
status:
first_appearance:
---

# ${v.NOTETITLE}

> [!info] Vehicle Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Type**:
> **Owner / Operator**:
> **Status**:

## Description

### Exterior



### Interior



## Specifications

| Attribute | Value |
|-----------|-------|
| Type      |       |
| Owner     |       |
| Crew      |       |
| Status    |       |

## Capabilities

### Performance



### Weapons / Defenses



### Special Systems



## History

### Origins / Construction



### Previous Owners

-

## Notable Journeys / Missions

-

## Crew & Passengers

| Person | Role |
|--------|------|
|        |      |

## Appearances

-

## Notes & Analysis

`;
}
function buildCreatureSpecies(v) {
  return `---
tags:
  - creature
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
classification:
sapient: false
status:
first_appearance:
---

# ${v.NOTETITLE}

> [!info] Species Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Classification**:
> **Sapient**: No
> **Status**:

## Physical Characteristics

### Appearance



### Size & Build



### Variants / Subspecies

-

## Abilities & Traits

### Natural Abilities

-

### Special Abilities

-

### Weaknesses

-

## Behavior & Ecology

### Behavior



### Habitat



### Diet



## Society & Culture *(if sapient)*

### Social Structure



### Language



### Beliefs



## History & Lore



## Known Individuals

| Name | Role | Notes |
|------|------|-------|
|      |      |       |

## Appearances

-

## Notes & Analysis

`;
}
function buildItemArtifact(v) {
  return `---
tags:
  - item
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
type:
origin:
current_holder:
status:
first_appearance:
---

# ${v.NOTETITLE}

> [!info] Item Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Type**:
> **Origin**:
> **Current Holder**:

## Description

### Appearance



### Notable Features



## Properties & Powers

-

## Limitations & Requirements

-

## History

### Origins / Creation



### Chain of Ownership

1.

### Key Events

-

## Significance to Story



## Appearances

-

## Notes & Analysis

`;
}
function buildFactionOrganization(v) {
  return `---
tags:
  - faction
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
type:
leader:
alignment:
status:
founded:
first_appearance:
---

# ${v.NOTETITLE}

> [!info] Faction Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Type**:
> **Leader**:
> **Alignment**:
> **Status**:

## Mission & Goals



## Structure

### Leadership

-

### Hierarchy



### Membership Requirements



## Methods & Resources



## History

### Founding



### Major Events

-

## Relationships

| Faction | Relationship |
|---------|-------------|
|         | Ally        |
|         | Enemy       |

## Members

| Character | Role | Status |
|-----------|------|--------|
|           |      |        |

## Appearances

-

## Notes & Analysis

`;
}
function buildTimelineEvent(v) {
  return `---
tags:
  - timeline-event
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
date_in_universe:
location:
significance:
---

# ${v.NOTETITLE}

> [!info] Event Overview
> **Show**: [[${v.MEDIATITLE}]]
> **Date (In-Universe)**:
> **Location**:
> **Significance**:

## What Happened



## Participants

| Person / Faction | Role |
|-----------------|------|
|                 |      |

## Causes & Context

### Direct Causes



### Broader Context



## Consequences

### Immediate Effects



### Long-term Impact



## Related Events

- **Preceded by**:
- **Led to**:

## Episode Reference

-

## Notes & Analysis

`;
}
function buildPlotThread(v) {
  return `---
tags:
  - plot-thread
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
type: main-arc
status: ongoing
introduced:
resolved:
---

# ${v.NOTETITLE}

> [!info] Plot Thread
> **Show**: [[${v.MEDIATITLE}]]
> **Type**: Main Arc
> **Status**: Ongoing
> **Introduced**:

## Overview



## Development

| Episode | Development | Notes |
|---------|-------------|-------|
|         |             |       |

## Key Players

-

## Connection to Other Threads

-

## Resolution

> [!success] Resolution
> *Status: Unresolved*

## Notes & Analysis

`;
}
function buildTheory(v) {
  return `---
tags:
  - theory
  - media/${v.MEDIASLUG}
media: "[[${v.MEDIATITLE}]]"
name: "${v.NOTETITLE}"
status: unconfirmed
confidence: medium
---

# ${v.NOTETITLE}

> [!question] Theory
> **Show**: [[${v.MEDIATITLE}]]
> **Status**: Unconfirmed
> **Confidence**: Medium

## The Theory



## Evidence Supporting

-

## Evidence Against

-

## Implications

### If True



### If False



## Related Theories

-

## Status Updates

| Date | Update |
|------|--------|
|      |        |

## Notes

`;
}

// src/CreateNoteModal.ts
var MediaSuggestModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, mediaList, callback) {
    super(app);
    this.mediaList = mediaList;
    this.callback = callback;
    this.setPlaceholder("Type to search your media library\u2026");
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "navigate" },
      { command: "\u21B5", purpose: "select" },
      { command: "esc", purpose: "cancel" }
    ]);
  }
  getItems() {
    return this.mediaList;
  }
  getItemText(item) {
    const icon = item.status === "watching" ? "\u25B6 " : item.status === "completed" ? "\u2713 " : "";
    return `${icon}${item.title}  [${item.type}]`;
  }
  renderSuggestion(item, el) {
    const media = item.item;
    el.createEl("div", { text: media.title, cls: "suggestion-title" });
    const sub = `${media.type}${media.year ? " \xB7 " + media.year : ""}  \u2014  ${media.status}`;
    el.createEl("div", { text: sub, cls: "suggestion-note" });
  }
  onChooseItem(item, _evt) {
    this.callback(item);
  }
};
var NoteTypeSuggestModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, noteTypes, callback) {
    super(app);
    this.noteTypes = noteTypes;
    this.callback = callback;
    this.setPlaceholder("What kind of note?");
  }
  getItems() {
    return this.noteTypes;
  }
  getItemText(item) {
    return item.label;
  }
  renderSuggestion(item, el) {
    const t = item.item;
    el.createEl("div", { text: t.label, cls: "suggestion-title" });
    el.createEl("div", { text: t.description, cls: "suggestion-note" });
  }
  onChooseItem(item, _evt) {
    this.callback(item);
  }
};
var NoteTitleModal = class extends import_obsidian3.Modal {
  constructor(app, noteType, media, defaultTitle, callback) {
    super(app);
    this.noteType = noteType;
    this.media = media;
    this.defaultTitle = defaultTitle;
    this.callback = callback;
    this.title = "";
    this.season = "";
    this.episode = "";
    this.title = defaultTitle;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("media-templates-modal");
    contentEl.createEl("h2", { text: `New ${this.noteType.label}` });
    contentEl.createEl("p", {
      text: `For: ${this.media.title}`,
      cls: "setting-item-description"
    });
    if (this.noteType.asksForSeason) {
      new import_obsidian3.Setting(contentEl).setName("Season").setDesc("Season number (leave blank for season 1)").addText((text) => {
        text.setPlaceholder("1").setValue(this.season).onChange((v) => this.season = v);
      });
    }
    if (this.noteType.asksForEpisode) {
      new import_obsidian3.Setting(contentEl).setName("Episode").setDesc("Episode number within the season").addText((text) => {
        text.setPlaceholder("1").setValue(this.episode).onChange((v) => this.episode = v);
      });
    }
    new import_obsidian3.Setting(contentEl).setName("Title").setDesc(`Name for this ${this.noteType.label.toLowerCase()} note`).addText((text) => {
      text.setPlaceholder(`${this.noteType.label} title\u2026`).setValue(this.title).onChange((v) => this.title = v);
      setTimeout(() => {
        text.inputEl.focus();
        text.inputEl.select();
      }, 50);
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") this.submit();
      });
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Create Note").setCta().onClick(() => this.submit())
    ).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => this.close())
    );
  }
  submit() {
    const finalTitle = this.title.trim();
    if (!finalTitle) {
      new import_obsidian3.Notice("Please enter a title.");
      return;
    }
    this.close();
    this.callback(finalTitle, this.season || "1", this.episode || "1");
  }
  onClose() {
    this.contentEl.empty();
  }
};
function openCreateNoteFlow(app, plugin) {
  const mediaList = plugin.settings.mediaLibrary;
  if (mediaList.length === 0) {
    new import_obsidian3.Notice(
      "No media in your library yet. Add some in Media Templates settings.",
      4e3
    );
    return;
  }
  new MediaSuggestModal(app, mediaList, (media) => {
    const relevantTypes = NOTE_TYPES.filter(
      (t) => !t.showOnlyFor || t.showOnlyFor.includes(media.type)
    );
    new NoteTypeSuggestModal(app, relevantTypes, (noteType) => {
      const defaultTitle = buildDefaultTitle(media, noteType);
      new NoteTitleModal(app, noteType, media, defaultTitle, (title, season, episode) => {
        plugin.createNote({ media, noteType: noteType.id, title, season, episode }).then((file) => {
          if (plugin.settings.openAfterCreate) {
            const leaf = app.workspace.getLeaf(false);
            leaf.openFile(file);
          }
          new import_obsidian3.Notice(`Created: ${title}`);
        }).catch((err) => {
          new import_obsidian3.Notice(`Error creating note: ${err.message}`);
          console.error("[Media Templates]", err);
        });
      }).open();
    }).open();
  }).open();
}
function buildDefaultTitle(media, noteType) {
  switch (noteType.id) {
    case "series-index":
      return media.title;
    case "season-overview":
      return `${media.title} \u2014 Season `;
    case "episode":
      return `${media.title} S01E01 \u2014 `;
    default:
      return "";
  }
}

// src/main.ts
var MediaTemplatesPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.api = {
      getMediaList: () => this.settings.mediaLibrary,
      getMedia: (id) => this.settings.mediaLibrary.find((m) => m.id === id),
      getMediaByTitle: (title) => this.settings.mediaLibrary.find(
        (m) => m.title.toLowerCase() === title.toLowerCase()
      ),
      getNoteTypes: () => NOTE_TYPES,
      createNote: (ctx) => this.createNote(ctx)
    };
    window["MediaTemplates"] = {
      plugin: this,
      api: this.api
    };
    this.addCommand({
      id: "create-media-note",
      name: "Create media note",
      callback: () => openCreateNoteFlow(this.app, this)
    });
    this.addCommand({
      id: "add-media-to-library",
      name: "Add media to library",
      callback: () => {
        new AddMediaModal(this.app, async (media) => {
          this.settings.mediaLibrary.push(media);
          await this.saveSettings();
          new import_obsidian4.Notice(`Added "${media.title}" to your library.`);
        }).open();
      }
    });
    this.addCommand({
      id: "create-series-index",
      name: "Create series index for media",
      callback: () => {
        const list = this.settings.mediaLibrary;
        if (!list.length) {
          new import_obsidian4.Notice("No media in library. Add some first.", 3e3);
          return;
        }
        openCreateNoteFlow(this.app, this);
      }
    });
    this.addSettingTab(new SettingsTab(this.app, this));
    console.log("[Media Templates] Plugin loaded.");
  }
  onunload() {
    delete window["MediaTemplates"];
    console.log("[Media Templates] Plugin unloaded.");
  }
  // ── Settings persistence ──────────────────────────────────────────────────
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ── Core note creation ────────────────────────────────────────────────────
  async createNote(ctx) {
    const noteTypeInfo = getNoteTypeInfo(ctx.noteType);
    const media = ctx.media;
    const mediaFolder = (media.noteFolder || `${this.settings.defaultMediaFolder}/${media.title}`).replace(/\/$/, "");
    const subFolder = noteTypeInfo.subFolder;
    const folderPath = (0, import_obsidian4.normalizePath)(
      subFolder ? `${mediaFolder}/${subFolder}` : mediaFolder
    );
    if (this.settings.autoCreateFolders) {
      await this.ensureFolder(folderPath);
    }
    const safeTitle = ctx.title.replace(/[\\/:*?"<>|]/g, "-");
    const filePath = (0, import_obsidian4.normalizePath)(`${folderPath}/${safeTitle}.md`);
    const existing = this.app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian4.TFile) {
      new import_obsidian4.Notice(`Note "${safeTitle}" already exists \u2014 opening it.`, 3e3);
      return existing;
    }
    const content = buildNoteContent(ctx);
    return await this.app.vault.create(filePath, content);
  }
  async ensureFolder(path) {
    const parts = path.split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const exists = this.app.vault.getAbstractFileByPath(current);
      if (!exists) {
        await this.app.vault.createFolder(current);
      } else if (!(exists instanceof import_obsidian4.TFolder)) {
        throw new Error(
          `Path "${current}" exists but is a file, not a folder.`
        );
      }
    }
  }
  // ── Convenience helper for QuickAdd / Templater scripts ──────────────────
  /** Returns a slug-safe version of the media title */
  static toSlug(title) {
    return toSlug(title);
  }
};
